import 'package:flutter/material.dart';

class Detail {
  final String title,
      subTitle,
      subTitle2,
      time,
      titleImage,
      subTitleImage,
      subTitleImage2;
  final int id, price;
  final double rate;
  Detail(
    this.id,
    this.title,
    this.subTitle,
    this.subTitle2,
    this.time,
    this.titleImage,
    this.subTitleImage,
    this.subTitleImage2,
    this.price,
    this.rate,
  );
}

List<Detail> details = [
  Detail(
    1,
    'Mathematics',
    'Integral',
    'Trigonometry',
    '15:00',
    'assets/images/maths.png',
    'assets/images/integral.png',
    'assets/images/trigonometry.png',
    10,
    4.6,
  ),
  Detail(
    2,
    'Chemistry',
    'Periodic System',
    'Atomic Theory',
    '18:00',
    'assets/images/chemistry2.png',
    'assets/images/periodic-table.png',
    'assets/images/atom.png',
    14,
    4.7,
  ),
  Detail(
    3,
    'Biology',
    'Plant Structure',
    'Virus',
    '12:00',
    'assets/images/biology.png',
    'assets/images/plant.png',
    'assets/images/virus.png',
    13,
    4.5,
  ),
  Detail(
    4,
    'English',
    'Grammar',
    'Listening',
    '15:40',
    'assets/images/language.png',
    'assets/images/grammar.png',
    'assets/images/listening.png',
    17,
    4.9,
  ),
  Detail(
    5,
    'Physics',
    'Newtons law',
    'Mechanical Wave',
    '14:30',
    'assets/images/physics.png',
    'assets/images/newton.png',
    'assets/images/wave.png',
    12,
    4.8,
  ),
  Detail(
    6,
    'Economy',
    'International Trade',
    'Capital Market',
    '17:00',
    'assets/images/economy.png',
    'assets/images/trade.png',
    'assets/images/market.png',
    17,
    4.8,
  ),
];
